name: Manual Build

on:
  workflow_dispatch

jobs:
  build:
    name: Build VSCode Win32 x64
    runs-on: windows-2022  # Windows Server 2022 runner
    timeout-minutes: 40
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Build VSCode Win32 x64
        run: npx gulp vscode-win32-x64

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vscode-win32-x64
          path: ../VSCode-win32-x64/  # Adjust this if the output folder is different
          retention-days: 7
